include:
  - path: appwrite/docker-compose.yml
    env_file: appwrite/.env

services:
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_APPWRITE_ENDPOINT: ${NEXT_PUBLIC_APPWRITE_ENDPOINT}
        NEXT_PUBLIC_APPWRITE_PROJECT_ID: ${NEXT_PUBLIC_APPWRITE_PROJECT_ID}
    container_name: wedding-gallery-frontend
    restart: unless-stopped
    ports:
      - "8006:3000"
